"""
2026 Alameda Little League Majors
Team:  Guardians
Date:  03/12
"""
TEAM = "Guardians"
DATE = "03/12"

# Hitting: all stats including 2B/3B/HR/SB/CS/E already merged
hitting = [
    {
          "name": "Drew B #4",
          "ab": 3,
          "r": 1,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 1,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Soren K #21",
          "ab": 3,
          "r": 0,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 2,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Conor F #24",
          "ab": 3,
          "r": 1,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 2,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Lennon D #34",
          "ab": 3,
          "r": 2,
          "h": 1,
          "rbi": 1,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 1,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Liam T #10",
          "ab": 3,
          "r": 0,
          "h": 1,
          "rbi": 2,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Patrick C #13",
          "ab": 1,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 2,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Luke T #29",
          "ab": 3,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Logan M #22",
          "ab": 2,
          "r": 1,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Lockie M #27",
          "ab": 1,
          "r": 1,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Carter H #7",
          "ab": 2,
          "r": 1,
          "h": 1,
          "rbi": 1,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Hunter D #6",
          "ab": 2,
          "r": 1,
          "h": 1,
          "rbi": 2,
          "bb": 0,
          "so": 1,
          "doubles": 1,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Zeke M #39",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 1,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
]

# Pitching: includes pitches/strikes/BF
pitching = [
    {
          "name": "Soren K #21",
          "ip": "3.0",
          "h": 1,
          "r": 3,
          "er": 2,
          "bb": 2,
          "so": 5,
          "pitches": 62,
          "strikes": 34,
          "bf": 12,
          "hbp": 0
        },
    {
          "name": "Drew B #4",
          "ip": "0.2",
          "h": 2,
          "r": 5,
          "er": 3,
          "bb": 2,
          "so": 0,
          "pitches": 35,
          "strikes": 17,
          "bf": 8,
          "hbp": 0
        },
    {
          "name": "Conor F #24",
          "ip": "1.1",
          "h": 5,
          "r": 4,
          "er": 4,
          "bb": 1,
          "so": 1,
          "pitches": 37,
          "strikes": 28,
          "bf": 9,
          "hbp": 0
        },
]
