"""
2026 Alameda Little League Majors
Team:  Brewers
Date:  03/14
"""
TEAM = "Brewers"
DATE = "03/14"

# Hitting: all stats including 2B/3B/HR/SB/CS/E already merged
hitting = [
    {
          "name": "Zach C #3",
          "ab": 5,
          "r": 2,
          "h": 2,
          "rbi": 1,
          "bb": 0,
          "so": 1,
          "doubles": 1,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Huston G #20",
          "ab": 4,
          "r": 3,
          "h": 3,
          "rbi": 4,
          "bb": 1,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Oliver R #41",
          "ab": 5,
          "r": 2,
          "h": 2,
          "rbi": 5,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 1,
          "hr": 1,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Luciano A #4",
          "ab": 2,
          "r": 0,
          "h": 1,
          "rbi": 1,
          "bb": 2,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "King N #13",
          "ab": 3,
          "r": 0,
          "h": 0,
          "rbi": 1,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Reece L #11",
          "ab": 3,
          "r": 0,
          "h": 1,
          "rbi": 0,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Zeke W #17",
          "ab": 4,
          "r": 1,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 2,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Theo D #24",
          "ab": 3,
          "r": 3,
          "h": 2,
          "rbi": 0,
          "bb": 1,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 3,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Clayton L #8",
          "ab": 2,
          "r": 3,
          "h": 2,
          "rbi": 0,
          "bb": 2,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 2,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Sebasti... #33",
          "ab": 3,
          "r": 3,
          "h": 2,
          "rbi": 1,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Walter C #2",
          "ab": 3,
          "r": 3,
          "h": 2,
          "rbi": 4,
          "bb": 1,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Miles M #7",
          "ab": 2,
          "r": 1,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
]

# Pitching: includes pitches/strikes/BF
pitching = [
    {
          "name": "Huston G #20",
          "ip": "3.2",
          "h": 2,
          "r": 2,
          "er": 0,
          "bb": 4,
          "so": 9,
          "pitches": 80,
          "strikes": 46,
          "bf": 18,
          "hbp": 0
        },
    {
          "name": "Zach C #3",
          "ip": "0.1",
          "h": 0,
          "r": 0,
          "er": 0,
          "bb": 0,
          "so": 0,
          "pitches": 2,
          "strikes": 2,
          "bf": 0,
          "hbp": 0
        },
    {
          "name": "Zeke W #17",
          "ip": "1.0",
          "h": 1,
          "r": 0,
          "er": 0,
          "bb": 0,
          "so": 0,
          "pitches": 6,
          "strikes": 5,
          "bf": 4,
          "hbp": 0
        },
    {
          "name": "Reece L #11",
          "ip": "1.0",
          "h": 0,
          "r": 0,
          "er": 0,
          "bb": 1,
          "so": 1,
          "pitches": 19,
          "strikes": 9,
          "bf": 4,
          "hbp": 0
        },
]
