"""
2026 Alameda Little League Majors
Team:  Giants
Date:  03/14
"""
TEAM = "Giants"
DATE = "03/14"

# Hitting: all stats including 2B/3B/HR/SB/CS/E already merged
hitting = [
    {
          "name": "Carver D #6",
          "ab": 3,
          "r": 1,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 2,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 2,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Cameron L #34",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 1,
          "bb": 1,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Jonah L #24",
          "ab": 2,
          "r": 0,
          "h": 1,
          "rbi": 0,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 1,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 2
        },
    {
          "name": "Jaxon M #2",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Thomas B #10",
          "ab": 3,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Griffin C #8",
          "ab": 1,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Benjami... #12",
          "ab": 1,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Boden N #41",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Michael H #7",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "River A #55",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Kai L #11",
          "ab": 2,
          "r": 1,
          "h": 2,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
]

# Pitching: includes pitches/strikes/BF
pitching = [
    {
          "name": "Cameron L #34",
          "ip": "2.2",
          "h": 1,
          "r": 3,
          "er": 0,
          "bb": 5,
          "so": 3,
          "pitches": 61,
          "strikes": 31,
          "bf": 16,
          "hbp": 0
        },
    {
          "name": "Thomas B #10",
          "ip": "0.2",
          "h": 1,
          "r": 4,
          "er": 4,
          "bb": 3,
          "so": 2,
          "pitches": 27,
          "strikes": 12,
          "bf": 6,
          "hbp": 0
        },
    {
          "name": "Jaxon M #2",
          "ip": "1.0",
          "h": 11,
          "r": 11,
          "er": 11,
          "bb": 2,
          "so": 1,
          "pitches": 47,
          "strikes": 27,
          "bf": 16,
          "hbp": 0
        },
    {
          "name": "Kai L #11",
          "ip": "1.2",
          "h": 6,
          "r": 3,
          "er": 2,
          "bb": 0,
          "so": 1,
          "pitches": 31,
          "strikes": 25,
          "bf": 11,
          "hbp": 0
        },
]
