"""
2026 Alameda Little League Majors
Team:  Giants
Date:  03/21
"""
TEAM = "Giants"
DATE = "03/21"

# Hitting: all stats including 2B/3B/HR/SB/CS/E already merged
hitting = [
    {
          "name": "Kai L #11",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Aiden G #22",
          "ab": 1,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 1,
          "e": 0
        },
    {
          "name": "Jonah L #24",
          "ab": 2,
          "r": 0,
          "h": 2,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 1,
          "hr": 0,
          "sb": 0,
          "cs": 1,
          "e": 1
        },
    {
          "name": "Cameron L #34",
          "ab": 1,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Carver D #6",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Thomas B #10",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Boden N #41",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 2,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Jaxon M #2",
          "ab": 2,
          "r": 1,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Griffin C #8",
          "ab": 2,
          "r": 0,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 1,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Michael H #7",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 2,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Benjami... #12",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 1,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
]

# Pitching: includes pitches/strikes/BF
pitching = [
    {
          "name": "Kai L #11",
          "ip": "1.1",
          "h": 3,
          "r": 4,
          "er": 3,
          "bb": 1,
          "so": 2,
          "pitches": 29,
          "strikes": 18,
          "bf": 9,
          "hbp": 0
        },
    {
          "name": "Thomas B #10",
          "ip": "0.2",
          "h": 4,
          "r": 3,
          "er": 1,
          "bb": 2,
          "so": 0,
          "pitches": 26,
          "strikes": 13,
          "bf": 8,
          "hbp": 0
        },
    {
          "name": "Jaxon M #2",
          "ip": "2.0",
          "h": 1,
          "r": 0,
          "er": 0,
          "bb": 0,
          "so": 3,
          "pitches": 26,
          "strikes": 18,
          "bf": 8,
          "hbp": 0
        },
    {
          "name": "Jonah L #24",
          "ip": "2.0",
          "h": 0,
          "r": 0,
          "er": 0,
          "bb": 0,
          "so": 6,
          "pitches": 21,
          "strikes": 18,
          "bf": 6,
          "hbp": 0
        },
]
