"""
2026 Alameda Little League Majors
Team:  Astros
Date:  03/10
"""
TEAM = "Astros"
DATE = "03/10"

# Hitting: all stats including 2B/3B/HR/SB/CS/E already merged
hitting = [
    {
          "name": "Connor Z #23",
          "ab": 2,
          "r": 2,
          "h": 2,
          "rbi": 2,
          "bb": 1,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Jordan C #3",
          "ab": 3,
          "r": 2,
          "h": 3,
          "rbi": 2,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Colton D #19",
          "ab": 3,
          "r": 2,
          "h": 2,
          "rbi": 3,
          "bb": 0,
          "so": 0,
          "doubles": 2,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Julian P #5",
          "ab": 3,
          "r": 2,
          "h": 3,
          "rbi": 1,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Carter F #24",
          "ab": 3,
          "r": 0,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Lukas I #11",
          "ab": 3,
          "r": 0,
          "h": 2,
          "rbi": 1,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Logan S #8",
          "ab": 3,
          "r": 0,
          "h": 1,
          "rbi": 2,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Kolin I #13",
          "ab": 3,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 2,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Niall F #12",
          "ab": 3,
          "r": 1,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Rio S #10",
          "ab": 3,
          "r": 1,
          "h": 2,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Max H #7",
          "ab": 3,
          "r": 1,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 2,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Benjami... #26",
          "ab": 3,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 3,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
]

# Pitching: includes pitches/strikes/BF
pitching = [
    {
          "name": "Carter F #24",
          "ip": "2.0",
          "h": 5,
          "r": 2,
          "er": 2,
          "bb": 1,
          "so": 2,
          "pitches": 35,
          "strikes": 22,
          "bf": 12,
          "hbp": 0
        },
    {
          "name": "Lukas I #11",
          "ip": "1.1",
          "h": 3,
          "r": 5,
          "er": 5,
          "bb": 4,
          "so": 1,
          "pitches": 40,
          "strikes": 18,
          "bf": 11,
          "hbp": 1
        },
    {
          "name": "Connor Z #23",
          "ip": "0.2",
          "h": 2,
          "r": 3,
          "er": 3,
          "bb": 2,
          "so": 0,
          "pitches": 19,
          "strikes": 8,
          "bf": 5,
          "hbp": 0
        },
    {
          "name": "Jordan C #3",
          "ip": "2.0",
          "h": 0,
          "r": 0,
          "er": 0,
          "bb": 0,
          "so": 5,
          "pitches": 27,
          "strikes": 21,
          "bf": 6,
          "hbp": 0
        },
]
