"""
2026 Alameda Little League Majors
Team:  Giants
Date:  03/18
"""
TEAM = "Giants"
DATE = "03/18"

# Hitting: all stats including 2B/3B/HR/SB/CS/E already merged
hitting = [
    {
          "name": "Kai L #11",
          "ab": 2,
          "r": 2,
          "h": 2,
          "rbi": 0,
          "bb": 1,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Aiden G #22",
          "ab": 2,
          "r": 1,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Jonah L #24",
          "ab": 3,
          "r": 0,
          "h": 2,
          "rbi": 3,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Carver D #6",
          "ab": 2,
          "r": 1,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Cameron L #34",
          "ab": 3,
          "r": 1,
          "h": 1,
          "rbi": 1,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Jaxon M #2",
          "ab": 3,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Thomas B #10",
          "ab": 3,
          "r": 0,
          "h": 2,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Boden N #41",
          "ab": 3,
          "r": 0,
          "h": 3,
          "rbi": 1,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Griffin C #8",
          "ab": 3,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Michael H #7",
          "ab": 1,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Benjami... #12",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 2,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 1
        },
    {
          "name": "River A #55",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 2,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
]

# Pitching: includes pitches/strikes/BF
pitching = [
    {
          "name": "Kai L #11",
          "ip": "2.0",
          "h": 4,
          "r": 1,
          "er": 0,
          "bb": 0,
          "so": 2,
          "pitches": 41,
          "strikes": 27,
          "bf": 10,
          "hbp": 0
        },
    {
          "name": "Jonah L #24",
          "ip": "2.0",
          "h": 7,
          "r": 6,
          "er": 1,
          "bb": 0,
          "so": 0,
          "pitches": 43,
          "strikes": 28,
          "bf": 15,
          "hbp": 0
        },
    {
          "name": "Cameron L #34",
          "ip": "0.2",
          "h": 3,
          "r": 6,
          "er": 2,
          "bb": 3,
          "so": 0,
          "pitches": 35,
          "strikes": 16,
          "bf": 9,
          "hbp": 0
        },
    {
          "name": "Jaxon M #2",
          "ip": "1.1",
          "h": 2,
          "r": 2,
          "er": 2,
          "bb": 0,
          "so": 1,
          "pitches": 19,
          "strikes": 13,
          "bf": 7,
          "hbp": 0
        },
]
