"""
2026 Alameda Little League Majors
Team:  Marlins
Date:  03/18
"""
TEAM = "Marlins"
DATE = "03/18"

# Hitting: all stats including 2B/3B/HR/SB/CS/E already merged
hitting = [
    {
          "name": "Julian W #3",
          "ab": 4,
          "r": 1,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Nico Y #0",
          "ab": 4,
          "r": 0,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Kaleo P #10",
          "ab": 3,
          "r": 2,
          "h": 3,
          "rbi": 2,
          "bb": 0,
          "so": 0,
          "doubles": 3,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Mayer H #5",
          "ab": 4,
          "r": 2,
          "h": 1,
          "rbi": 2,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 1,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Frankie G #28",
          "ab": 3,
          "r": 2,
          "h": 1,
          "rbi": 0,
          "bb": 1,
          "so": 2,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Henry B #16",
          "ab": 2,
          "r": 0,
          "h": 1,
          "rbi": 0,
          "bb": 1,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Cassius... #24",
          "ab": 3,
          "r": 2,
          "h": 2,
          "rbi": 1,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 2
        },
    {
          "name": "Wilder E #17",
          "ab": 3,
          "r": 2,
          "h": 2,
          "rbi": 1,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Jax H #23",
          "ab": 3,
          "r": 2,
          "h": 1,
          "rbi": 1,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Wyatt M #11",
          "ab": 1,
          "r": 1,
          "h": 0,
          "rbi": 2,
          "bb": 1,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Shawn M #12",
          "ab": 3,
          "r": 1,
          "h": 2,
          "rbi": 2,
          "bb": 0,
          "so": 0,
          "doubles": 1,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Andreas... #27",
          "ab": 3,
          "r": 0,
          "h": 1,
          "rbi": 2,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
]

# Pitching: includes pitches/strikes/BF
pitching = [
    {
          "name": "Julian W #3",
          "ip": "5.0",
          "h": 6,
          "r": 2,
          "er": 1,
          "bb": 3,
          "so": 7,
          "pitches": 86,
          "strikes": 52,
          "bf": 25,
          "hbp": 0
        },
    {
          "name": "Wilder E #17",
          "ip": "1.0",
          "h": 4,
          "r": 3,
          "er": 3,
          "bb": 1,
          "so": 1,
          "pitches": 22,
          "strikes": 16,
          "bf": 8,
          "hbp": 0
        },
]
