"""
2026 Alameda Little League Majors
Team:  Padres
Date:  03/19
"""
TEAM = "Padres"
DATE = "03/19"

# Hitting: all stats including 2B/3B/HR/SB/CS/E already merged
hitting = [
    {
          "name": "Arthur B #2",
          "ab": 2,
          "r": 1,
          "h": 1,
          "rbi": 1,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "RJ F #22",
          "ab": 3,
          "r": 1,
          "h": 1,
          "rbi": 1,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Orion M #13",
          "ab": 3,
          "r": 1,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 2,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Miles D #24",
          "ab": 2,
          "r": 1,
          "h": 1,
          "rbi": 0,
          "bb": 1,
          "so": 0,
          "doubles": 0,
          "triples": 1,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Adrian T #50",
          "ab": 3,
          "r": 0,
          "h": 0,
          "rbi": 1,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Cruz B #34",
          "ab": 2,
          "r": 1,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Ezekiel C #3",
          "ab": 3,
          "r": 1,
          "h": 2,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 1
        },
    {
          "name": "AJ L #28",
          "ab": 2,
          "r": 1,
          "h": 1,
          "rbi": 2,
          "bb": 1,
          "so": 1,
          "doubles": 1,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Samuel G #7",
          "ab": 1,
          "r": 1,
          "h": 1,
          "rbi": 1,
          "bb": 2,
          "so": 0,
          "doubles": 0,
          "triples": 1,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Donovan K #51",
          "ab": 2,
          "r": 1,
          "h": 2,
          "rbi": 1,
          "bb": 1,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Brody E #44",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
]

# Pitching: includes pitches/strikes/BF
pitching = [
    {
          "name": "RJ F #22",
          "ip": "1.1",
          "h": 1,
          "r": 1,
          "er": 0,
          "bb": 0,
          "so": 3,
          "pitches": 24,
          "strikes": 17,
          "bf": 6,
          "hbp": 0
        },
    {
          "name": "Samuel G #7",
          "ip": "1.2",
          "h": 4,
          "r": 3,
          "er": 2,
          "bb": 1,
          "so": 3,
          "pitches": 39,
          "strikes": 26,
          "bf": 10,
          "hbp": 0
        },
    {
          "name": "Brody E #44",
          "ip": "1.0",
          "h": 1,
          "r": 1,
          "er": 0,
          "bb": 1,
          "so": 1,
          "pitches": 16,
          "strikes": 8,
          "bf": 5,
          "hbp": 0
        },
    {
          "name": "Miles D #24",
          "ip": "2.0",
          "h": 1,
          "r": 0,
          "er": 0,
          "bb": 3,
          "so": 2,
          "pitches": 34,
          "strikes": 16,
          "bf": 10,
          "hbp": 0
        },
]
