"""
2026 Alameda Little League Majors
Team:  White Sox
Date:  03/19
"""
TEAM = "White Sox"
DATE = "03/19"

# Hitting: all stats including 2B/3B/HR/SB/CS/E already merged
hitting = [
    {
          "name": "Julius N #30",
          "ab": 3,
          "r": 1,
          "h": 2,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Adrien R #6",
          "ab": 3,
          "r": 1,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Ace B #44",
          "ab": 2,
          "r": 1,
          "h": 1,
          "rbi": 2,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 1,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Jack G #27",
          "ab": 2,
          "r": 0,
          "h": 1,
          "rbi": 1,
          "bb": 1,
          "so": 0,
          "doubles": 1,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Hudson C #22",
          "ab": 3,
          "r": 1,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 1,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Sam E #11",
          "ab": 3,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 2,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Edward M #24",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 2,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Brayden K #7",
          "ab": 2,
          "r": 1,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 2,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Philip T #17",
          "ab": 1,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Lou V #14",
          "ab": 1,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Beni R #5",
          "ab": 2,
          "r": 0,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Jaiden N #3",
          "ab": 1,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
]

# Pitching: includes pitches/strikes/BF
pitching = [
    {
          "name": "Hudson C #22",
          "ip": "2.0",
          "h": 1,
          "r": 2,
          "er": 2,
          "bb": 3,
          "so": 0,
          "pitches": 37,
          "strikes": 21,
          "bf": 9,
          "hbp": 0
        },
    {
          "name": "Brayden K #7",
          "ip": "1.1",
          "h": 3,
          "r": 4,
          "er": 3,
          "bb": 1,
          "so": 0,
          "pitches": 29,
          "strikes": 16,
          "bf": 8,
          "hbp": 0
        },
    {
          "name": "Julius N #30",
          "ip": "0.0",
          "h": 2,
          "r": 1,
          "er": 1,
          "bb": 1,
          "so": 0,
          "pitches": 12,
          "strikes": 6,
          "bf": 3,
          "hbp": 0
        },
    {
          "name": "Jack G #27",
          "ip": "0.2",
          "h": 1,
          "r": 1,
          "er": 0,
          "bb": 1,
          "so": 2,
          "pitches": 14,
          "strikes": 8,
          "bf": 4,
          "hbp": 0
        },
    {
          "name": "Adrien R #6",
          "ip": "1.0",
          "h": 0,
          "r": 1,
          "er": 0,
          "bb": 0,
          "so": 3,
          "pitches": 13,
          "strikes": 10,
          "bf": 4,
          "hbp": 0
        },
    {
          "name": "Edward M #24",
          "ip": "1.0",
          "h": 2,
          "r": 0,
          "er": 0,
          "bb": 1,
          "so": 1,
          "pitches": 13,
          "strikes": 7,
          "bf": 4,
          "hbp": 0
        },
]
