"""
2026 Alameda Little League Majors
Team:  White Sox
Date:  03/07
"""
TEAM = "White Sox"
DATE = "03/07"

# Hitting: all stats including 2B/3B/HR/SB/CS/E already merged
hitting = [
    {
          "name": "Julius N #30",
          "ab": 2,
          "r": 0,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Adrien R #6",
          "ab": 2,
          "r": 1,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Ace B #44",
          "ab": 1,
          "r": 0,
          "h": 0,
          "rbi": 1,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Sam E #11",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Brayden K #7",
          "ab": 1,
          "r": 1,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Hudson C #22",
          "ab": 1,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 1,
          "e": 0
        },
    {
          "name": "Jack G #27",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 3
        },
    {
          "name": "Edward M #24",
          "ab": 1,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 1,
          "e": 0
        },
    {
          "name": "Lou V #14",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Jaiden N #3",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 2,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Philip T #17",
          "ab": 1,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
]

# Pitching: includes pitches/strikes/BF
pitching = [
    {
          "name": "Adrien R #6",
          "ip": "1.1",
          "h": 1,
          "r": 2,
          "er": 1,
          "bb": 2,
          "so": 4,
          "pitches": 37,
          "strikes": 20,
          "bf": 8,
          "hbp": 0
        },
    {
          "name": "Hudson C #22",
          "ip": "1.2",
          "h": 1,
          "r": 1,
          "er": 0,
          "bb": 2,
          "so": 0,
          "pitches": 38,
          "strikes": 21,
          "bf": 9,
          "hbp": 0
        },
    {
          "name": "Ace B #44",
          "ip": "1.2",
          "h": 2,
          "r": 1,
          "er": 0,
          "bb": 2,
          "so": 3,
          "pitches": 35,
          "strikes": 19,
          "bf": 9,
          "hbp": 0
        },
    {
          "name": "Sam E #11",
          "ip": "0.1",
          "h": 0,
          "r": 0,
          "er": 1,
          "bb": 1,
          "so": 0,
          "pitches": 6,
          "strikes": 2,
          "bf": 2,
          "hbp": 0
        },
]
