"""
2026 Alameda Little League Majors
Team:  Astros
Date:  03/16
"""
TEAM = "Astros"
DATE = "03/16"

# Hitting: all stats including 2B/3B/HR/SB/CS/E already merged
hitting = [
    {
          "name": "Connor Z #23",
          "ab": 2,
          "r": 1,
          "h": 0,
          "rbi": 0,
          "bb": 2,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Jordan C #3",
          "ab": 4,
          "r": 2,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 2,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 2,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Colton D #19",
          "ab": 2,
          "r": 2,
          "h": 1,
          "rbi": 1,
          "bb": 1,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Julian P #5",
          "ab": 3,
          "r": 3,
          "h": 3,
          "rbi": 2,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 1,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Carter F #24",
          "ab": 3,
          "r": 1,
          "h": 1,
          "rbi": 2,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Lukas I #13",
          "ab": 1,
          "r": 1,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Logan S #8",
          "ab": 2,
          "r": 0,
          "h": 1,
          "rbi": 0,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Niall F #12",
          "ab": 3,
          "r": 0,
          "h": 0,
          "rbi": 1,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Rio S #10",
          "ab": 3,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 3,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Kolin I #11",
          "ab": 3,
          "r": 0,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 2,
          "doubles": 1,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Max H #7",
          "ab": 2,
          "r": 1,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Benjami... #26",
          "ab": 3,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 3,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
]

# Pitching: includes pitches/strikes/BF
pitching = [
    {
          "name": "Carter F #24",
          "ip": "3.0",
          "h": 2,
          "r": 1,
          "er": 0,
          "bb": 2,
          "so": 4,
          "pitches": 48,
          "strikes": 32,
          "bf": 13,
          "hbp": 0
        },
    {
          "name": "Rio S #10",
          "ip": "2.0",
          "h": 1,
          "r": 1,
          "er": 0,
          "bb": 1,
          "so": 3,
          "pitches": 29,
          "strikes": 17,
          "bf": 8,
          "hbp": 0
        },
    {
          "name": "Logan S #8",
          "ip": "1.0",
          "h": 3,
          "r": 1,
          "er": 1,
          "bb": 0,
          "so": 2,
          "pitches": 20,
          "strikes": 16,
          "bf": 6,
          "hbp": 0
        },
]
