"""
2026 Alameda Little League Majors
Team:  Giants
Date:  03/10
"""
TEAM = "Giants"
DATE = "03/10"

# Hitting: all stats including 2B/3B/HR/SB/CS/E already merged
hitting = [
    {
          "name": "Carver D #6",
          "ab": 1,
          "r": 2,
          "h": 0,
          "rbi": 0,
          "bb": 2,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Kai L #11",
          "ab": 2,
          "r": 1,
          "h": 1,
          "rbi": 1,
          "bb": 1,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Cameron L #34",
          "ab": 3,
          "r": 2,
          "h": 2,
          "rbi": 4,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 1,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Jonah L #24",
          "ab": 3,
          "r": 0,
          "h": 2,
          "rbi": 1,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 1,
          "hr": 0,
          "sb": 0,
          "cs": 1,
          "e": 0
        },
    {
          "name": "Thomas B #10",
          "ab": 2,
          "r": 1,
          "h": 1,
          "rbi": 1,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Jaxon M #2",
          "ab": 2,
          "r": 1,
          "h": 1,
          "rbi": 0,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Griffin C #8",
          "ab": 3,
          "r": 0,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Aiden G #22",
          "ab": 3,
          "r": 1,
          "h": 2,
          "rbi": 1,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Benjami... #12",
          "ab": 1,
          "r": 1,
          "h": 0,
          "rbi": 1,
          "bb": 2,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Boden N #41",
          "ab": 3,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 3,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Michael H #7",
          "ab": 1,
          "r": 1,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "River A #55",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 1,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
]

# Pitching: includes pitches/strikes/BF
pitching = [
    {
          "name": "Jonah L #24",
          "ip": "3.0",
          "h": 10,
          "r": 6,
          "er": 6,
          "bb": 1,
          "so": 6,
          "pitches": 64,
          "strikes": 44,
          "bf": 20,
          "hbp": 0
        },
    {
          "name": "Jaxon M #2",
          "ip": "2.0",
          "h": 7,
          "r": 5,
          "er": 5,
          "bb": 0,
          "so": 3,
          "pitches": 36,
          "strikes": 23,
          "bf": 13,
          "hbp": 0
        },
    {
          "name": "Cameron L #34",
          "ip": "1.0",
          "h": 0,
          "r": 0,
          "er": 0,
          "bb": 0,
          "so": 3,
          "pitches": 16,
          "strikes": 11,
          "bf": 3,
          "hbp": 0
        },
]
