"""
2026 Alameda Little League Majors
Team:  Guardians
Date:  03/21
"""
TEAM = "Guardians"
DATE = "03/21"

# Hitting: all stats including 2B/3B/HR/SB/CS/E already merged
hitting = [
    {
          "name": "Drew B #4",
          "ab": 2,
          "r": 0,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 1,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 2
        },
    {
          "name": "Soren K #21",
          "ab": 2,
          "r": 0,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Conor F #24",
          "ab": 1,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 1,
          "e": 0
        },
    {
          "name": "Lennon D #34",
          "ab": 2,
          "r": 1,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 1,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Liam T #10",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 2,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Patrick C #13",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 1,
          "e": 0
        },
    {
          "name": "Logan M #22",
          "ab": 2,
          "r": 0,
          "h": 2,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 1,
          "e": 1
        },
    {
          "name": "Hunter D #6",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 2,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Lockie M #27",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Carter H #7",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Luke T #29",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Zeke M #39",
          "ab": 1,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
]

# Pitching: includes pitches/strikes/BF
pitching = [
    {
          "name": "Conor F #24",
          "ip": "3.0",
          "h": 4,
          "r": 4,
          "er": 2,
          "bb": 4,
          "so": 4,
          "pitches": 70,
          "strikes": 36,
          "bf": 20,
          "hbp": 0
        },
    {
          "name": "Soren K #21",
          "ip": "2.0",
          "h": 2,
          "r": 2,
          "er": 1,
          "bb": 1,
          "so": 5,
          "pitches": 42,
          "strikes": 22,
          "bf": 9,
          "hbp": 0
        },
    {
          "name": "Lennon D #34",
          "ip": "1.0",
          "h": 0,
          "r": 1,
          "er": 0,
          "bb": 2,
          "so": 0,
          "pitches": 23,
          "strikes": 11,
          "bf": 6,
          "hbp": 0
        },
]
