"""
2026 Alameda Little League Majors
Team:  Yankees
Date:  03/21
"""
TEAM = "Yankees"
DATE = "03/21"

# Hitting: all stats including 2B/3B/HR/SB/CS/E already merged
hitting = [
    {
          "name": "Adam H #12",
          "ab": 3,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Thomas D #5",
          "ab": 3,
          "r": 1,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Hudson P #2",
          "ab": 1,
          "r": 1,
          "h": 0,
          "rbi": 0,
          "bb": 2,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Henry S #47",
          "ab": 2,
          "r": 2,
          "h": 1,
          "rbi": 2,
          "bb": 1,
          "so": 1,
          "doubles": 1,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Severin... #15",
          "ab": 3,
          "r": 1,
          "h": 2,
          "rbi": 1,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Max M #14",
          "ab": 3,
          "r": 1,
          "h": 1,
          "rbi": 1,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 1,
          "e": 0
        },
    {
          "name": "Roland M #99",
          "ab": 2,
          "r": 0,
          "h": 1,
          "rbi": 0,
          "bb": 1,
          "so": 0,
          "doubles": 1,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Ben B #26",
          "ab": 2,
          "r": 0,
          "h": 1,
          "rbi": 2,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Brixton L #9",
          "ab": 3,
          "r": 1,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Owen S #11",
          "ab": 2,
          "r": 0,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 1,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Benny M #13",
          "ab": 1,
          "r": 0,
          "h": 0,
          "rbi": 1,
          "bb": 1,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Jet S #17",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 2,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
]

# Pitching: includes pitches/strikes/BF
pitching = [
    {
          "name": "Roland M #99",
          "ip": "2.0",
          "h": 0,
          "r": 0,
          "er": 0,
          "bb": 1,
          "so": 3,
          "pitches": 32,
          "strikes": 21,
          "bf": 8,
          "hbp": 0
        },
    {
          "name": "Hudson P #2",
          "ip": "2.0",
          "h": 2,
          "r": 0,
          "er": 0,
          "bb": 0,
          "so": 1,
          "pitches": 31,
          "strikes": 19,
          "bf": 10,
          "hbp": 0
        },
    {
          "name": "Ben B #26",
          "ip": "0.0",
          "h": 0,
          "r": 2,
          "er": 2,
          "bb": 2,
          "so": 0,
          "pitches": 8,
          "strikes": 0,
          "bf": 2,
          "hbp": 0
        },
    {
          "name": "Adam H #12",
          "ip": "0.1",
          "h": 1,
          "r": 2,
          "er": 2,
          "bb": 2,
          "so": 0,
          "pitches": 14,
          "strikes": 3,
          "bf": 3,
          "hbp": 0
        },
    {
          "name": "Henry S #7",
          "ip": "1.2",
          "h": 4,
          "r": 1,
          "er": 1,
          "bb": 1,
          "so": 0,
          "pitches": 27,
          "strikes": 16,
          "bf": 9,
          "hbp": 0
        },
]
