"""
2026 Alameda Little League Majors
Team:  Marlins
Date:  03/12
"""
TEAM = "Marlins"
DATE = "03/12"

# Hitting: all stats including 2B/3B/HR/SB/CS/E already merged
hitting = [
    {
          "name": "Julian W #3",
          "ab": 1,
          "r": 2,
          "h": 0,
          "rbi": 0,
          "bb": 2,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Nico Y #0",
          "ab": 3,
          "r": 2,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Kaleo P #10",
          "ab": 3,
          "r": 2,
          "h": 2,
          "rbi": 5,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 1,
          "sb": 0,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Mayer H #5",
          "ab": 3,
          "r": 0,
          "h": 1,
          "rbi": 2,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Shawn M #12",
          "ab": 1,
          "r": 1,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 1,
          "e": 1
        },
    {
          "name": "Frankie G #28",
          "ab": 1,
          "r": 1,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Wilder E #17",
          "ab": 1,
          "r": 1,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 2
        },
    {
          "name": "Jax H #23",
          "ab": 1,
          "r": 1,
          "h": 0,
          "rbi": 0,
          "bb": 1,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Cassius... #24",
          "ab": 2,
          "r": 0,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Wyatt M #11",
          "ab": 2,
          "r": 0,
          "h": 1,
          "rbi": 0,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
    {
          "name": "Henry B #16",
          "ab": 2,
          "r": 2,
          "h": 2,
          "rbi": 1,
          "bb": 0,
          "so": 0,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 1
        },
    {
          "name": "Andreas... #27",
          "ab": 2,
          "r": 0,
          "h": 0,
          "rbi": 0,
          "bb": 0,
          "so": 1,
          "doubles": 0,
          "triples": 0,
          "hr": 0,
          "sb": 0,
          "cs": 0,
          "e": 0
        },
]

# Pitching: includes pitches/strikes/BF
pitching = [
    {
          "name": "Wilder E #17",
          "ip": "2.0",
          "h": 3,
          "r": 3,
          "er": 3,
          "bb": 1,
          "so": 3,
          "pitches": 38,
          "strikes": 24,
          "bf": 10,
          "hbp": 0
        },
    {
          "name": "Mayer H #5",
          "ip": "2.0",
          "h": 1,
          "r": 1,
          "er": 0,
          "bb": 1,
          "so": 3,
          "pitches": 32,
          "strikes": 21,
          "bf": 9,
          "hbp": 0
        },
    {
          "name": "Julian W #3",
          "ip": "1.0",
          "h": 4,
          "r": 4,
          "er": 4,
          "bb": 1,
          "so": 0,
          "pitches": 21,
          "strikes": 11,
          "bf": 8,
          "hbp": 0
        },
    {
          "name": "Kaleo P #10",
          "ip": "1.0",
          "h": 0,
          "r": 0,
          "er": 0,
          "bb": 0,
          "so": 2,
          "pitches": 12,
          "strikes": 10,
          "bf": 4,
          "hbp": 0
        },
]
